### ISSUE TITLE
Got nil pointer error when executing SET command with empty value

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/device-sdk-go#1021]
# 🐞 Bug Report

### Description and Minimal Reproduction
The error variable was redeclared in the case section, so the error checking didn't catch the error and throw the nil pointer result.

Recreate the issue with device-simple service:
1. Prepare device profile file:
```
apiVersion: "v2"
name: "Simple-Device"

deviceResources:
  -
    name: "Float32Value"
    isHidden: false
    description: "Float32Value value."
    properties:
        valueType: "Float32"
        readWrite: "RW"
  -
    name: "Float64Value"
    isHidden: false
    description: "Float32Value value."
    properties:
      valueType: "Float64"
      readWrite: "RW"
```   
2. Prepare device toml file
```
[[DeviceList]]
  Name = "Simple-Device01"
  ProfileName = "Simple-Device"
  Description = "Example of Simple Device"
  Labels = [ "industrial" ]
  [DeviceList.Protocols]
  [DeviceList.Protocols.other]
    Address = "simple01"
    Port = "300"
```
3. Run core services and device-simple

4. Execute SET command
```
curl --location --request PUT 'http://0.0.0.0:59882/api/v2/device/name/Simple-Device01/Float64Value' \
--header 'Content-Type: application/json' \
--data-raw '{
    "Float64Value": ""
}'
```
## 🔥 Exception or Error
<pre><code>
level=DEBUG ts=2021-09-29T02:18:12.843950446Z app=device-bacnet source=command.go:234 msg="Application - writeDeviceResource: writing deviceResource: analog_input_0-deadband; X-Correlation-ID: d84fe545-2831-4627-b25d-09d6dd98a998"
2021/09/29 02:18:12 http: panic serving 172.24.0.9:56774: runtime error: invalid memory address or nil pointer dereference
goroutine 866 [running]:
net/http.(*conn).serve.func1(0xc000472960)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x922b80, 0xcdccd0)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/edgexfoundry/device-sdk-go/v2/internal/application.(*CommandProcessor).WriteDeviceResource(0xc0003c7228, 0xc0003f93a0, 0xc)
	/xrt-xpert-bridge/device-sdk-go-private/internal/application/command.go:255 +0x406
github.com/edgexfoundry/device-sdk-go/v2/internal/application.CommandHandler(0x960000, 0xc00036d440, 0x24, 0xc0003fc4b0, 0xc0003fc5a0, 0x0, 0x0, 0xc00031f6e0, 0x0, 0x0, ...)
	/xrt-xpert-bridge/device-sdk-go-private/internal/application/command.go:109 +0x6a8
github.com/edgexfoundry/device-sdk-go/v2/internal/controller/http.(*RestController).Command(0xc0003bf140, 0xa72720, 0xc00021f180, 0xc0003ecc00)
	/xrt-xpert-bridge/device-sdk-go-private/internal/controller/http/command.go:62 +0x2d8
net/http.HandlerFunc.ServeHTTP(0xc0001bac90, 0xa72720, 0xc00021f180, 0xc0003ecc00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
...
</code></pre>

## 🌍  Your Environment
**EdgeX Version:**
Main branch

**Anything else relevant?**
