### ISSUE TITLE
Writable.LogLevel isn't checked for values when not using consul

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/device-sdk-go#325]
For example with this:

```toml
[Writable]
  LogLevel = 'not_a_real_log_level'
```

No warnings or anything are output. Unclear if this is an issue yet or not, and it's also unclear if this causes a problem when using consul.
