### ISSUE TITLE
device-simple: delay before fist device is added

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#566]
While testing Chris's PR for issue #560, I noticed a problem I'd seen before with device-virtual, and now am seeing when running device-simple in the foreground while testing Chris's PR, namely that there seems to be a 2 1/2 minute delay from when the service starts to when the first device is added:

```
level=INFO ts=2020-08-14T22:54:51.174413977Z app=device-simple source=message.go:58 msg="Service started in: 31.475793ms"
level=INFO ts=2020-08-14T22:54:51.174212392Z app=device-simple source=autodiscovery.go:19 msg="AutoDiscovery stopped: disabled by configuration"
level=INFO ts=2020-08-14T22:57:21.180722587Z app=device-simple source=device.go:58 msg="Added device: Simple-Device01"
```
Note, I was running device-simple against the latest/stable edgexfoundry snap (1.2.1-20200721+14637657 / r2388). I made the following changes to the configuration of device-simple, I had removed everything from Device-Simple.yaml except for a single deviceResource:

```
name: "Simple-Device"
manufacturer: "Simple Corp."
model: "SP-01"
labels:
  - "modbus"
description: "Example of Simple Device"

deviceResources:
  -
    name: "Image"
    description: "Visual representation of Switch state."
    properties:
      value:
        { type: "Binary", readWrite: "R", mediaType: "JPG" }
      units:
        { type: "Binary", readWrite: "R", defaultValue: "On/Off" }
```
And I removed the **AutoEvent** for **Switch** in **configuration.toml**.

Notice how the "Added device:" message is almost 2:30 after the "Service started in:" message.

Steps to reproduce:

```
$ sudo snap install edgexfoundry
$ cd device-sdk-go
$ make
$ cd example/device-simple
$ ./device-simple
```
I also re-tried with --registry=consul://localhost:8500, and I see the same behavior.

Version: v1.2.4-dev.2 + the change from Chris' PR for issue #560 
OS: Ubuntu 18.04 LTS Desktop
