### ISSUE TITLE
How to generate a yaml file available for edgex？

### ISSUE THREAD

**Issue by xuexiqiangzhe** [edgexfoundry/device-sdk-go#723]
Hello:
I have a Yaml used to work for edgex.I Use“ gopkg.in/yaml . V2 "package handle Yaml to struct, then modify stuct, and then transfer to yaml.
The generated yaml file cannot be used
Error in starting device microservice
```
level=ERROR ts=2021-01-11T02:58:01.23501223Z app=device-simple source= profiles.go:88 msg="Add Device Profile: /home/yxh/go/src/ github.com/edgexfoundry/device -simple/cmd/device-simple/res/Simple-Driver_ generated.yaml to Core Metadata failed: 400 - Object and DeviceResource are both blank\n"
```
How to generate a yaml file available for edgex？
Can someone help me? Thank you!

**Comment by xuexiqiangzhe** [comment]
These are the two yaml, simple driver before and after the operation. Simple-Driver_available.yaml can be used by edgex, but Simple-Driver_generated.yaml can't when used by edgex
```level=ERROR ts=2021-01-11T02:58:01.23501223Z app=device-simple source= profiles.go:88 msg="Add Device Profile: /home/yxh/go/src/ github.com/edgexfoundry/device -simple/cmd/device-simple/res/Simple-Driver_ generated.yaml to Core Metadata failed: 400 - Object and DeviceResource are both blank\n"```
[Yaml before and after operation.zip](https://github.com/edgexfoundry/device-sdk-go/files/5793927/Yaml.before.and.after.operation.zip)

**Comment by cloudxxx8** [comment]
@xuexiqiangzhe we are going to announce a Device Configuration Tool which can help you generate the Device Profile from a Web GUI.
However, in your case, the generated YAML doesn't match the original YAML.  According to the error message, this issue is in the deviceCommands section.  The original one contains deviceResource, and the generated one doesn't:

original:
```
deviceCommands:
  -
    name: "random2"
    get:
      - { operation: "get", deviceResource: "randomnumber" }
  -
    name: "Image"
    get:
      - { operation: "get", deviceResource: "Image" }
  -
    name: "Rotation"
    get:
      - { operation: "get", deviceResource: "Xrotation" }
      - { operation: "get", deviceResource: "Yrotation" }
      - { operation: "get", deviceResource: "Zrotation" }
    set:
      - { operation: "set", deviceResource: "Xrotation", parameter: "0" }
      - { operation: "set", deviceResource: "Yrotation", parameter: "0" }
      - { operation: "set", deviceResource: "Zrotation", parameter: "0" }
```

generated:
```
deviceCommands:
- name: random2
  get:
  - operation: get
    object: ""
    property: ""
    parameter: ""
- name: Image
  get:
  - operation: get
    object: ""
    property: ""
    parameter: ""
- name: Rotation
  get:
  - operation: get
    object: ""
    property: ""
    parameter: ""
  - operation: get
    object: ""
    property: ""
    parameter: ""
  - operation: get
    object: ""
    property: ""
    parameter: ""
```

Please remove the object field, which is deprecated, and add the deviceResource field
